update

# Common packages to install with brew
install autojump
install zsh
install wget
install git
install tree
install ruby
install python3
# A faster ack
install ag
install vim --with-python3

cleanup
