update

# Common packages to install with brew
install autojump
install zsh
install wget
install git
install tree
install ruby
install python3
# A faster ack
install ag
# Both terminal vim and macvim are nice
install vim --with-python3
install mvim --with-python3

cleanup
